### ISSUE TITLE
Fix the layouting bug.

### ISSUE THREAD

**Issue by aoitofu** [aoitofu/MILK#3]
For example, run example1 and resize the showed window. The placed widgets will be shrink and off to the left. But no one wants the behaviour like that.
 Layouting process also has problems. Widgets refer the parent window to make window re-layout. This makes circular dependencies.

## ToDo
- [x] Add property 'needLayout' to class Base Widget.
- [x] Change to make windows re-layout when needLayout become true.
- [x] Fix label's auto-size-adjusting process.

### Label's auto-size-adjusting process
 Label creates its textures at redrawing process. So adjusting its size will be late. The solution is that the label creates textures when window instance is set to it.
